### ISSUE TITLE
Post-Quantum Encryption

### ISSUE THREAD

**Issue by ghost** [Peergos/Peergos#237]
It's a great project but why don't you guys add the support of Post-Quantum Encryption ? Tried McBits(asymmetric algorithm uses McEliece cryptosystem using binary based Goppa Codes ? Or QcBits which uses Quasi-Cyclic MDPC based McEliece? Or Maybe NTRUEncrypt(Lattice-based cryptosystem)?

**Comment by ianopolous** [comment]
Hi deltaspectre, 

Thanks for dropping by! We've literally just merged the move to hashes of public keys in the protocol which smooths the way for moving to post-quantum crypto. I think at the moment though there isn't a clear winning candidate for post quantum algorithms. But still, we are hoping to start working on enabling some of the currently recommended candidates soon. 

Already in Peergos, most of your files are resistent to decryption by a quantum computer, the only exceptions are files that are shared between users. This is because to decrypt your own files only relies on hashing and symmetric algorithms that aren't significantly weakened by a quantum computer.
