### ISSUE TITLE
State of this project (Alpha)

### ISSUE THREAD

**Issue by matteodem** [Peergos/Peergos#308]
Great job on this project! :+1: 

Is there any roadmap for this year? I'm considering to use it for https://github.com/matteodem/sounds-social/issues/1 

But it being in "alpha" is kind of worrying. What is your recommendation for now? Wait?

**Comment by ianopolous** [comment]
Hi Matt,

Thanks for your support! 

We have a roadmap here: https://github.com/Peergos/Peergos/blob/master/RoadMap.md
It is mainly in alpha because we need an independent security audit. However, that costs ~20k so we need to raise money for that. The apis and datastructures are relatively stable. 

For your particular use case - we can already play audio files directly in the browser. For example:
https://demo.peergos.net/#pQd8rmrEhBN1RbDLK1ioBnFF4YLgvPAmte3ypNDiwshMJJip9Dbbgw4t/EttruJNmGoKRERj8LdWJ1Ev5EAUfJgvi6sqvB8Wfztxp/5Pf7SvL6ucoMZuK8675zLCwYR27UhiHhduyEPDAMrBSj9MyvVD5?open=true

**Comment by matteodem** [comment]
Do you know any projects that use peergos in production?

**Comment by ianopolous** [comment]
I'm not sure what production means in this context. The idea is that there is one global peergos network. Individuals will be able to run their own server, but it will talk to all the other Peergos servers (over Tor eventually). But at the moment I'm not aware of anyone using the demo network (demo.peergos.net) in a deployed app elsewhere if that's what you mean.

**Comment by matteodem** [comment]
Yeah I'm sorry that's what I meant. As in if somebody is using peergos in an application to distribute files.

**Comment by ianopolous** [comment]
The other usage limit at the moment is, because we're hosting it all ourselves, each user is limited to 200mb on our server. One we support self hosting you can increase that just by running your own server (which you could still access through ours).

**Comment by matteodem** [comment]
What constitues a user? There's still quite a lot of questions that I have, but I don't think Github is the right place to discuss it. Peergos sounds like it holds a lot of potential though. 

What's your preferred way of contacting you?

**Comment by ianopolous** [comment]
We've recently launched our public alpha:
https://peergos.org/blog#alpha_release_june_2019_

A user is someone who's created an account on the Peergos network, which in practice means claiming a username in the pki. You can contact me directly on a twitter dm initially.
