### ISSUE TITLE
Possible CHAMP collapse algorithm bug

### ISSUE THREAD

**Issue by rvagg** [Peergos/Peergos#421]
Hey @ianopolous, I'm enjoying your implementation of the CHAMP algorithm, it's much more readable and flexible version than the POC in Steindorfer's original. I'm working on one in JavaScript, primarily for IPLD and this has been extremely helpful to get the algorithm right but I fell down a hole that I think your implementation also suffers from:

https://github.com/Peergos/Peergos/blob/05e6cd4b1b307f37729df2b212815a8572bd69e8/src/peergos/shared/hamt/Champ.java#L410-L436

In `remove()`, when collapsing a Node up into a parent level, the buckets are left intact, which doesn't make sense for those elements when they are at the parent level or any higher and share the same hash prefix. This is taken care of in `copyAndMigrateFromNodeToInline()` for what likely ends up being the majority case where those elements need to be transferred into a bucket in a parent level.

But the case where the collapsed element ends up being the new root node fails because you're returning a new root that has elements spread across >1 buckets when they should be in a single one. The parent ends up malformed, some or all `get()`s will fail and adding new data is going to result in corruption.

https://github.com/Peergos/Peergos/blob/05e6cd4b1b307f37729df2b212815a8572bd69e8/src/peergos/shared/hamt/Champ.java#L453-L456

I solved this by pushing logic similar to what you have in `copyAndMigrateFromNodeToInline()` into the creation of original collapsed node: move all pairs into a single bucket at the depth=0 position, sorting it and bubble that up. You could then make `copyAndMigrateFromNodeToInline()` simpler by removing the iterate-over-buckets block and just extracting the single bucket that now exists and replacing the node with it, no sorting or iterating required. Since https://github.com/msteindorfer/oopsla15-artifact/tree/master/pdb.values/src/org/eclipse/imp/pdb/facts/util only implements a max-collisions of 2 it doesn't need this overhead but I'm finding that for the case where your backing store is slow (like IPFS!) that having larger buckets is often going to be much more sensible.

I discovered this with a test case that uses identity hashes so I could predictably force the creation of a deeply nested set of nodes just for a few elements, then a single delete should collapse back up into a well-formed tree or root. e.g. keys that hash to bytes such as `[x,x,x,1]`, `[x,x,x,2]`, `[x,x,x,3]` with a bit/prefix length of `4` and max-collisions of `2` should result in a 6 parent nodes and a child with entries spread across 3 buckets. Removing just one should bring you back to a root node with a single bucket with 2 entries.

**Comment by ianopolous** [comment]
G'day Rod!

Thanks for your feedback, and great catch! Always great to get an extra pair of eyes on your code. The Go version is also quite readable. Bear in mind that if you want to be compatible with the go implementation then you can't vary the bitwidth and max collisions as we do, and I expect the serialization is different as well. 

You might also be interested that we use this Java implementation in the browser by cross compiling it to Javascript via GWT. 

I've got a test that triggers the problem using your example here:
https://github.com/Peergos/Peergos/compare/test/champ-delete

Luckily this doesn't affect Peergos as we don't use delete, because we're using it as a OR-set CRDT - so we put a tombstone value rather than remove. Though I'll still fix it.
